Instantiate sequalize and connect to the database
tech-university-india/uhi-onboarding-backend pull request #1
Opened 2023-01-26 08:21 UTC by Saatwik-S

This pull request consists of:
- Creation of Patient Table with few basic columns
- Instantiation of Sequalize
- Addition of dotenv module

In order to connect to the database, one should make a .env file in the main directory ( the directory that contains index.js ) and then add the following variables:

- **DBNAME**
- **DBPASSWORD**
- **DBUSER**
- **DBHOST**
- **DBPORT**

2023-01-26 08:36 UTC, rkdixit96 requested changes

2023-01-26 08:36 UTC, rkdixit96 commented on package.json
> +  "author": "McKinsey and Company",
Remove this author

2023-01-26 08:36 UTC, rkdixit96 commented on src/database/models/patientModel.js
> +module.exports = Patient;
Eslint is not working or is not configured properly

2023-01-26 08:36 UTC, rkdixit96 commented on src/routes/onboarding/onboardingRoutes.js
> +module.exports = router;
General rule - If the folder is called route - no need to mention again in file name. Please change even the model file as well

2023-01-26 08:36 UTC, rkdixit96 commented on src/database/models/patientModel.js
> +module.exports = Patient;
Lets use predefined style for linting

2023-01-26 09:10 UTC, rkdixit96 approved these changes

2023-02-02 10:27 UTC, NiranjanBorawar commented on src/index.js
> +
Let's configure prettier also
or any other default file formatter

2023-02-02 10:28 UTC, NiranjanBorawar commented on src/index.js
> +
It will avoid these whitespaces and newlines

2023-03-28 07:19 UTC, closed without merging