Create ABDM JWT Parser and apply code enforcing via linting ( standard style )
tech-university-india/uhi-onboarding-backend pull request #3
Opened 2023-01-26 11:08 UTC by Saatwik-S

Created a JWT Parser which fetches the token from sandbox and then saves it locally in a file. 
It doesn't fetch another token from the sandbox until and unless the current one expires.

Additional Changes:
Added code enforcing with eslint ( standard style )

2023-01-28 05:03 UTC, rkdixit96 requested changes

2023-01-28 05:03 UTC, rkdixit96 commented on src/util/abdm.js
> +  console.log(Date.now())
Remove console.log

2023-01-28 05:03 UTC, rkdixit96 commented on src/util/abdm.js
> + */
I don't think the comment is necessary - The function is self explanatory

2023-01-28 10:11 UTC, rkdixit96 approved these changes

2023-02-02 10:30 UTC, NiranjanBorawar approved these changes

2023-03-02 09:15 UTC, merged