chore: add readme file
tech-university-india/uhi-onboarding-backend pull request #7
Opened 2023-02-10 04:31 UTC by xentro-sam

2023-02-10 07:08 UTC, NiranjanBorawar approved these changes

2023-02-20 11:16 UTC, rkdixit96 requested changes
This README.md should have information about the onboarding backend and not UHI

2023-03-02 09:42 UTC, xentro-sam commented
Requested changes implemented. Please review

2023-03-15 09:03 UTC, souris-dev approved these changes

2023-03-28 07:18 UTC, maitra100 approved these changes

2023-04-13 06:37 UTC, closed without merging