Feat/abdm user abha creation
tech-university-india/uhi-onboarding-backend pull request #8
Opened 2023-02-10 04:57 UTC by yashasva01

2023-02-12 09:01 UTC, rkdixit96 requested changes

2023-02-12 09:01 UTC, rkdixit96 commented on index.js
> +const sequelize = require('./src/services/database/dbConnection')
Not needed here

2023-02-12 09:01 UTC, rkdixit96 commented on src/fetchedToken.txt
> +eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBbFJiNVdDbThUbTlFSl9JZk85ejA2ajlvQ3Y1MXBLS0ZrbkdiX1RCdkswIn0.eyJleHAiOjE2NzUyMjc2OTAsImlhdCI6MTY3NTIyNzA5MCwianRpIjoiNTI5NjJkOGQtMzMxMi00OTA1LWFhYmQ
Do a git rm

2023-02-12 09:01 UTC, rkdixit96 commented on src/routes/onboarding.js
> +//router.post('users/', user.resendOTP)
Remove commented route

2023-02-12 09:02 UTC, rkdixit96 commented
Remove all commented code @yashasva01

2023-02-12 09:05 UTC, yashasva01 commented
> Remove all commented code @yashasva01

okay, will edit.

2023-02-12 10:28 UTC, yashasva01 commented on index.js
> +const sequelize = require('./src/services/database/dbConnection')
Done

2023-02-12 10:28 UTC, yashasva01 commented on index.js
> +//   .catch(console.log)
Done

2023-02-12 10:29 UTC, yashasva01 commented on src/util/abdm.js
> +  const response = await fetch('https://gjgew5guy33vice6fauegfokme0dyaxy.lambda-url.us-east-1.on.aws/?code=krkedikhayenge')
Done

2023-02-12 10:42 UTC, yashasva01 commented on src/util/userOnboardingApi.js
> +    const response = await axios.post('https://healthidsbx.abdm.gov.in/api/v1/registration/aadhaar/createHealthIdWithPreVerified', {
Done

2023-02-12 12:36 UTC, rkdixit96 requested changes
Remove .DS_Store file. Add that to .gitignore as well

2023-02-12 12:36 UTC, rkdixit96 commented on src/util/userOnboardingApi.js
> +
All of these are services

2023-02-12 12:36 UTC, rkdixit96 commented on src/config/User/onboardingEndpoints.js
> +
Extract out base url - `https://healthidsbx.abdm.gov.in` from all these endpoints
So when we move to PROD we have to make a change in only one place

2023-02-12 12:36 UTC, rkdixit96 commented on src/util/userOnboardingApi.js
> +
Just make these API calls directly in the service

2023-02-14 12:32 UTC, maitra100 commented on src/config/User/onboardingEndpoints.js
> +
done

2023-02-17 06:09 UTC, NiranjanBorawar commented on database/migrations/20230213052619-create-users.js
> +        type: Sequelize.INTEGER
can we check type of all the fields once again
like emailId should be string, dayOfBirth and yearOfBirth we can keep as Integer, Gender we can try to keep as ENUM

2023-02-17 06:10 UTC, NiranjanBorawar commented on database/migrations/20230213053309-create-user-location.js
> +        type: Sequelize.STRING
pinCode should be INTEGER

2023-02-17 10:15 UTC, maitra100 commented on database/migrations/20230213052619-create-users.js
> +        type: Sequelize.INTEGER
emailId is a foreign key referencing the primary key of User_email table. dayOfBirth and yearOfBirth have been removed in the next migration files. We'll change the type of gender.

2023-02-17 12:02 UTC, maitra100 commented on database/migrations/20230213053309-create-user-location.js
> +        type: Sequelize.STRING
Krishna said let it be string.

2023-02-18 06:03 UTC, maitra100 commented on src/util/userOnboardingApi.js
> +
done

2023-02-24 13:35 UTC, rkdixit96 approved these changes

2023-03-13 05:42 UTC, SaatwikRishi approved these changes

2023-03-13 05:42 UTC, merged